version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      kotlin-tooling:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.dokka*"
          - "org.jetbrains.kotlinx*"
      quality-tooling:
        patterns:
          - "dev.detekt*"
          - "org.jlleitschuh.gradle.ktlint*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
